db.url=jdbc:mysql://127.0.0.1:3307/piprojet1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&sessionVariables=character_set_client=utf8mb4,character_set_connection=utf8mb4,character_set_results=utf8mb4&connectTimeout=5000&socketTimeout=5000
db.username=root
db.password=

