# Configuration SMTP Gmail - AfkArt
mail.enabled=true
mail.preview=true

email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.smtp.username=issrabenghrib04@gmail.com

# REMPLACE cette ligne par ton mot de passe d'application Gmail (16 caracteres)
# Genere sur : https://myaccount.google.com/security > Mots de passe des applications
# Exemple : email.smtp.password=abcdabcdabcdabcd
email.smtp.password=zqtv bcud tqpm avtv

email.from=issrabenghrib04@gmail.com
email.from.name=AfkArt
