CREATE DATABASE IF NOT EXISTS pi_projet;
USE pi_projet;

CREATE TABLE IF NOT EXISTS `user` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `nom` VARCHAR(100) NOT NULL,
    `prenom` VARCHAR(100) NOT NULL,
    `email` VARCHAR(150) NOT NULL UNIQUE,
    `motDePasse` VARCHAR(255) NOT NULL,
    `role` VARCHAR(50) NOT NULL DEFAULT 'CLIENT',
    `dateCreation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `statut` VARCHAR(50) NOT NULL DEFAULT 'ACTIF',
    `telephone` VARCHAR(30) NULL
);
